"""
Django settings for myproject project.
Generated by 'django-admin startproject' using Django 6.0.5.
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(#exonetfinu6g2k5jhlmk0+*odf(*-)wmugr$e41lcy-pgm$w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
DEBUG = False

#ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['*']
# Application definition
INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Maktaba zetu za kazi
    'rest_framework',
    'rest_framework.authtoken', 
    'rest_framework_api_key',   

    # App yetu ya kazi
    'table', 
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        # Hapa tunaweka sheria kwa kila plugin kiwanda!
        'media_downloader': '2/day',  # Mwisho request 2 kwa siku kwa majaribio
        'ocr_service': '50/day',
        'qr_service': '100/day',
    },
}

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
import dj_database_url
import os

# Kama upo Render, itasoma kamba ya Supabase. Kama ipo local na haujaweka, itatumia SQLite ya majaribio
DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL', 'sqlite:///db.sqlite3'),
        conn_max_age=600
    )
}

# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'
# RUHUSA ZA CORS KWA AJILI YA FRONTEND YA VERCEL
CORS_ALLOWED_ORIGINS = [
    "https://api-collection-fontend-poku.vercel.app",
    "https://tend-poku.vercel.app",  # Imeongezwa kutokana na domain ya sasa kwenye picha
]

# Ukipenda kuruhusu localhost wakati unatecha local:
CORS_ALLOW_HEADERS = [
    "accept",
    "authorization",
    "content-type",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-api-key",
]
CORS_ALLOW_ALL_ORIGINS = True

from corsheaders.defaults import default_headers

CORS_ALLOW_HEADERS = list(default_headers) + [
    "X-API-Key",
]
# Celery Configuration
#CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
#CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
#import os
#import os

# Django inaangalia: "Je, kuna REDIS_URL mtandaoni?" 
# Kama ipo (kule Render), inaichukua. Kama haipo (kwenye simu), inatumia localhost!
CELERY_BROKER_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
CELERY_RESULT_BACKEND = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')

# Kama tupo live Render itasoma REDIS_URL ya mtandao, la sivyo itatumia localhost
#REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')

#CELERY_BROKER_URL = REDIS_URL
#CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
# Mstari huu unaiambia Django ikutekeleza task ya Celery hapo hapo (Synchronously) 
# bila kuhitaji kuongea na Redis. Ni nzuri sana kwa ajili ya kufanya testing.
#CELERY_TASK_ALWAYS_EAGER = True
#CELERY_BROKER_CONNECTION_RETRY_ON_STARTAGE = True


import os

# URL itakayoonekana kwenye kivinjari (Mfano: /media/downloads/video.mp4)
MEDIA_URL = '/media/'

# Folder halisi ndani ya simu yako ambapo ma-file yatakuwepo
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'endesha-usafi-kila-dakika-10': {
        'task': 'polls.tasks.safisha_media_files_task',
        'schedule': 600.0, # Muda wa sekunde (sekunde 600 ni sawa na dakika 10)
        # Kama mbeleni ukitaka itumie saa maalum, unaweza kuweka crontab()
    },
ion
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Static files
STATIC_URL = 'static/'

# Celery Configuration
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/2'
CELERY_RESULT_BACKEND = 'redis://127.0.0.1:6379/2'
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
# Mstari huu unaiambia Django ikutekeleza task ya Celery hapo hapo (Synchronously) 
# bila kuhitaji kuongea na Redis. Ni nzuri sana kwa ajili ya kufanya testing.
#CELERY_TASK_ALWAYS_EAGER = True
#CELERY_BROKER_CONNECTION_RETRY_ON_STARTAGE = True


import os

# URL itakayoonekana kwenye kivinjari (Mfano: /media/downloads/video.mp4)
MEDIA_URL = '/media/'

# Folder halisi ndani ya simu yako ambapo ma-file yatakuwepo
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'endesha-usafi-kila-dakika-10': {
        'task': 'plugins.media_downloader.tasks.safisha_media_files_task',
        'schedule': 60.0, # Muda wa sekunde (sekunde 600 ni sawa na dakika 10)
        # Kama mbeleni ukitaka itumie saa maalum, unaweza kuweka crontab() 
}}
