# Generated by Django 6.0.5 on 2026-06-22 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_test_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='user',
        ),
        migrations.AddField(
            model_name='test',
            name='format_type',
            field=models.CharField(choices=[('video', 'Video (MP4)'), ('audio', 'Audio (MP3)')], default='video', max_length=10),
        ),
        migrations.AddField(
            model_name='test',
            name='quality',
            field=models.CharField(choices=[('360p', '360p (Low)'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('best', 'Best Quality')], default='720p', max_length=10),
        ),
        migrations.AlterField(
            model_name='test',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
