# Generated by Django 6.0.5 on 2026-06-23 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_test_user_test_format_type_test_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
