# Generated by Django 6.0.5 on 2026-07-07 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=1000)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('format_type', models.CharField(choices=[('video', 'Video (MP4)'), ('audio', 'Audio (MP3)')], default='video', max_length=10)),
                ('quality', models.CharField(choices=[('360p', '360p (Low)'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('best', 'Best Quality')], default='720p', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
