# Generated by Django 6.0.5 on 2026-07-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('table', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginLimitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin_name', models.CharField(choices=[('media_downloader', 'Media Downloader')], max_length=50, unique=True)),
                ('max_requests_per_day', models.IntegerField(default=2)),
            ],
        ),
        migrations.CreateModel(
            name='UserPluginUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_prefix', models.CharField(max_length=8)),
                ('plugin_name', models.CharField(max_length=50)),
                ('request_count', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('api_key_prefix', 'plugin_name', 'date')},
            },
        ),
    ]
